export const  gameSenceObject = {
  Lottery_type:[
    {
      id:1,
      name: '重庆时时彩',
      play_group:[
        {
          id:1,
          name:'五星',
          play_list:[
            {
              id:'963261194281533441',
              name:'直选复式',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:5,
                row_title:['万位','千位','百位','十位','个位']
              }
            },
            {
              id:'963261194478665730',
              name:'直选单式',
              ui_obj:{
                style_type_name:'style4',
                col:10,
                row:3,
                row_title:['百位','十位','个位']
              }
            },
            {
              id:'963261194478665732',
              name:'直选组合',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:5,
                row_title:['万位','千位','百位','十位','个位']
              }
            },
            {
              id:'963261194478665734',
              name:'组选120',
              ui_obj:{
                style_type_name:'style2',
                col:10,
                row:1,
                row_title:[]
              }
            },
            {
              id:'963261194478665736',
              name:'组选60',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:2,
                row_title:['二重号','单号']
              }
            },
            {
              id:'963261194478665738',
              name:'组选30',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:2,
                row_title:['二重号','单号']
              }
            },
            {
              id:'963261194478665740',
              name:'组选20',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:2,
                row_title:['三重号','单号']
              }
            },
            {
              id:'963261194478665742',
              name:'组选10',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:2,
                row_title:['三重号','单二重号']
              }
            },
            {
              id:'963261194478665744',
              name:'组选5',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:2,
                row_title:['四重号','单号']
              }
            }
          ]
        },
        {
          id:2,
          name:'四星',
          play_list:[
            {
              id:'963261194478665746',
              name:'直选复式',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:4,
                row_title:['千位','百位','十位','个位']
              }
            },
            {
              id:'963261194478665748',
              name:'直选单式',
              ui_obj:{
                style_type_name:'style4',
                col:10,
                row:3,
                row_title:['百位','十位','个位']
              }
            },
            {
              id:'963261194478665750',
              name:'直选组合',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:4,
                row_title:['千位','百位','十位','个位']
              }
            },
            {
              id:'963261194478665752',
              name:'组24',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:1,
                row_title:['组24']
              }
            },
            {
              id:'963261194478665754',
              name:'组选12',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:2,
                row_title:['二重号','单号']
              }
            },
            {
              id:'963261194478665756',
              name:'组选6',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:1,
                row_title:['二重号']
              }
            },
            {
              id:'963261194478665758',
              name:'组选4',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:2,
                row_title:['三重号','单号']
              }
            }
          ]
        },
        {
          id:3,
          name:'后三码',
          play_list:[
            {
              id:'963261194478665760',
              name:'直选复式',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:3,
                row_title:['百位','十位','个位']
              }
            },
            {
              id:'963261194545774707',
              name:'千个',
              ui_obj:{
                style_type_name:'style4',
                col:3,
                row:1,
                row_title:['万:千']
              }
            },
            {
              id:'963261194478665764',
              name:'和值',
              ui_obj:{
                style_type_name:'style5',
                col:27,
                start:0,
                row:1,
                row_title:['直选和值']
              }
            },
            {
              id:'963261194478665766',
              name:'组三',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:1,
                row_title:['组三']
              }
            },
            {
              id:'963261194478665768',
              name:'组六',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:1,
                row_title:['组六']
              }
            },
            {
              id:'963261194478665770',
              name:'混合',
              ui_obj:{
                style_type_name:'style4',
                col:10,
                row:1,
                row_title:['组六']
              }
            },
            {
              id:'963261194478665772',
              name:'组选和值',
              ui_obj:{
                style_type_name:'style5',
                start:1,
                col:27,
                row:1,
                row_title:['组选和值']
              }
            }
          ]
        },
        {
          id:14,
          name:'龙虎斗',
          play_list:[
            {
              id:'963261194545774645',
              name:'万个',
              ui_obj:{
                style_type_name:'style3',
                col:3,
                row:1,
                row_title:['万:千']
              }
            },
            {
              id:'963261194545774647',
              name:'千个',
              ui_obj:{
                style_type_name:'style3',
                col:3,
                row:1,
                row_title:['万:千']
              }
            }
          ]
        },
        {
          id:4,
          name:'前三码',
          play_list:[
            {
              id:'963261194478665762',
              name:'单式',
              ui_obj:{
                style_type_name:'style4',
                col:3,
                row:1,
                row_title:['万:千']
              }
            },
            {
              id:'963261194545774675',
              name:'复式',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:3,
                row_title:['万位','千位','百位']
              }
            },
            {
              id:'963261194545774693',
              name:'和值',
              ui_obj:{
                style_type_name:'style5',
                col:28,
                start:0,
                row:1,
                row_title:['直选和值']
              }
            },
            {
              id:'963261194545774679',
              name:'组三',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:1,
                row_title:['组三']
              }
            },
            {
              id:'963261194545774721',
              name:'组六',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:1,
                row_title:['组六']
              }
            },
            {
              id:'963261194545774697',
              name:'混合',
              ui_obj:{
                style_type_name:'style4',
                col:28,
                start:0,
                row:1,
                row_title:['直选和值']
              }
            },
            {
              id:'963261194545774725',
              name:'组选和值',
              ui_obj:{
                style_type_name:'style5',
                col:27,
                start:1,
                row:1,
                row_title:['组选和值']
              }
            }
          ]
        },
        {
          id:4,
          name:'中三码',
          play_list:[
            {
              id:'963261194478665762',
              name:'单式',
              ui_obj:{
                style_type_name:'style4',
                col:3,
                row:1,
                row_title:['万:千']
              }
            },
            {
              id:'963261194545774675',
              name:'复式',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:3,
                row_title:['万位','千位','百位']
              }
            },
            {
              id:'963261194545774693',
              name:'和值',
              ui_obj:{
                style_type_name:'style5',
                col:28,
                start:0,
                row:1,
                row_title:['直选和值']
              }
            },
            {
              id:'963261194545774679',
              name:'组三',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:1,
                row_title:['组三']
              }
            },
            {
              id:'963261194545774721',
              name:'组六',
              ui_obj:{
                style_type_name:'style1',
                col:10,
                row:1,
                row_title:['组六']
              }
            },
            {
              id:'963261194545774697',
              name:'混合',
              ui_obj:{
                style_type_name:'style4',
                col:28,
                start:0,
                row:1,
                row_title:['直选和值']
              }
            },
            {
              id:'963261194545774725',
              name:'组选和值',
              ui_obj:{
                style_type_name:'style5',
                col:27,
                start:1,
                row:1,
                row_title:['组选和值']
              }
            }
          ]
        }
      ]
    }
  ]
}
